- hosts: jenkins
  gather_facts: no

  tasks:
    - name: Create Deployment
      k8s:
        state: present
        namespace: default
        definition:
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: nginx
          spec:
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                nodeSelector:
                  node: web
                containers:
                - image: "repush/cicdproject:nginx{{ lookup('env', 'BUILD_NUMBER') }}"
                  name: nginx
                  ports:
                  - containerPort: 80
                    protocol: TCP
    - name: Create Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: default
            labels:
              app: nginx
          spec:
            type: NodePort
            selector:
              app: nginx
            ports:
              - port: 80
                targetPort: 80
                nodePort: 32123
